// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ReportDetail: typeof import('./src/components/ReportDetail.vue')['default']
    ReportTable: typeof import('./src/components/ReportTable.vue')['default']
    UpIcon: typeof import('./src/components/UpIcon.vue')['default']
    UpLayout: typeof import('./src/components/UpLayout.vue')['default']
    UpLayoutChild: typeof import('./src/components/UpLayoutChild.vue')['default']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
  }
}

export { }
