// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttachmentInline: typeof import('./src/components/inline/attachment-inline.vue')['default']
    AttachmentsInline: typeof import('./src/components/inline/attachments-inline.vue')['default']
    ContinentSummary: typeof import('./src/components/summaries/continent-summary.vue')['default']
    DateInline: typeof import('./src/components/inline/date-inline.vue')['default']
    DocumentList: typeof import('./src/components/collections/document-list.vue')['default']
    DocumentPagesSummary: typeof import('./src/components/summaries/document-pages-summary.vue')['default']
    DocumentsList: typeof import('./src/components/sections/documents-list.vue')['default']
    LocationInline: typeof import('./src/components/inline/location-inline.vue')['default']
    Newsletter: typeof import('./src/components/forms/newsletter.vue')['default']
    Plural: typeof import('./src/components/widgets/plural.vue')['default']
    ReferenceInline: typeof import('./src/components/inline/reference-inline.vue')['default']
    ReferencesInline: typeof import('./src/components/inline/references-inline.vue')['default']
    ReportFilters: typeof import('./src/components/forms/report-filters.vue')['default']
    ReportInline: typeof import('./src/components/inline/report-inline.vue')['default']
    ReportList: typeof import('./src/components/collections/report-list.vue')['default']
    ReportMap: typeof import('./src/components/collections/report-map.vue')['default']
    ReportOverview: typeof import('./src/components/sections/report-overview.vue')['default']
    ReportResult: typeof import('./src/components/summaries/report-result.vue')['default']
    ReportsList: typeof import('./src/components/sections/reports-list.vue')['default']
    ReportsTable: typeof import('./src/components/sections/reports-table.vue')['default']
    ReportTags: typeof import('./src/components/collections/report-tags.vue')['default']
    SamfordQuote: typeof import('./src/components/widgets/samford-quote.vue')['default']
    SourceInline: typeof import('./src/components/inline/source-inline.vue')['default']
  }
}

export { }
